package software.aoc.day7.part2;

import org.junit.Test;
import java.io.IOException;
import java.io.InputStream;
import static org.assertj.core.api.Assertions.assertThat;

public class TachyonManifoldTest {
    String tachyon_map = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """;

    @Test
    public void given_tachyon_map_should_account_number_of_split_beams() {
        assertThat(TachyonManifold.with("""
                                             ...S...
                                             ...^...
                                             ..^...^
                                             .^..^..
                                             .......
                                             """).totalPaths()).isEqualTo(5);
        assertThat(TachyonManifold.with(tachyon_map).totalPaths()).isEqualTo(40);
    }

    @Test
    public void reward() throws IOException {
        try (InputStream inputStream = TachyonManifoldTest.class.getResourceAsStream("/day7/input7.txt")) {
            assertThat(TachyonManifold.with(new String(inputStream.readAllBytes())).totalPaths()).isEqualTo(5921061943075L);
        }
    }
}